# STAGE 1: BUILDER
FROM golang:1.25.5-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

# NOTE the specific build path for the parser executable
RUN go build -ldflags "-s -w" -o /go-distributed-parser ./cmd/parser 

# STAGE 2: FINAL
FROM scratch
COPY --from=builder /go-distributed-parser /go-distributed-parser
# Copy config directory to the same location as binary
COPY --from=builder /app/config /config

ENTRYPOINT ["/go-distributed-parser"]