# STAGE 1: BUILDER
FROM golang:1.25.5-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

# NOTE the specific build path for the collector executable
RUN go build -ldflags "-s -w" -o /go-distributed-collector ./cmd/collector 

# STAGE 2: FINAL
FROM scratch
COPY --from=builder /go-distributed-collector /go-distributed-collector
COPY --from=builder /app/config /config

ENTRYPOINT ["/go-distributed-collector"]